stages:
- checks
- test
- deploy

pre-commit-check:
  stage: checks
  image: python:3.11-bullseye
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

.tox-setup:
  before_script:
    - python -V
    - pip install tox

pylint:
  stage: checks
  extends: .tox-setup
  image: python:3.11-bullseye
  script:
    - tox -e pylint

test:
  stage: test
  extends: .tox-setup
  image: python:3.11-bullseye
  script:
    - tox -e py
    - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
  stage: deploy
  image: python:3.11-bullseye
  before_script:
    - pip install -U pip twine wheel build
  script:
    - python -m build
    - twine upload dist/*
  only:
    - tags
